-- 코드를 입력하세요
SELECT OUTS.ANIMAL_ID, OUTS.ANIMAL_TYPE, OUTS.NAME FROM ANIMAL_OUTS AS OUTS
    LEFT OUTER JOIN ANIMAL_INS AS INS
    ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
    WHERE OUTS.SEX_UPON_OUTCOME != INS.SEX_UPON_INTAKE
    ORDER BY OUTS.ANIMAL_ID