SELECT O.YEAR, O.MONTH, COUNT(DISTINCT U.USER_ID) AS PURCHAED_USERS, ROUND(COUNT(DISTINCT U.USER_ID) / (
    SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = '2021'), 1) AS PUCHASED_RATIO
FROM USER_INFO U
JOIN (
    SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, USER_ID
    FROM ONLINE_SALE
    GROUP BY YEAR, MONTH, USER_ID
) O
    ON O.USER_ID = U.USER_ID
WHERE
    YEAR(JOINED) = '2021'
GROUP BY O.YEAR, O.MONTH
ORDER BY O.YEAR, O.MONTH;